#!/bin/bash
<<DOC
#Name         :Akshitha S
#Date         :20/10/2023
#Description  :Read 'n' and generate a pattern given below:
                Test case: 1
                        ./pattern_1.sh
                        Enter the number: 4
                        1
                        1 2
                        1 2 3
                        1 2 3 4
#Sample Input : Enter the number: 4
#Sample Output: 1
                1 2
                1 2 3
                1 2 3 4
DOC
read -p "Enter the number: " n  #read the input n
for row in `seq $n`             #run the row for n times
do
    for col in `seq $row`       #to run col loop for row times
    do
        echo -n "$col "         #print the col values
    done
    echo
done
