#!/bin/bash
<<DOC
#Name         :Akshitha S
#Date         :03/11/2023
#Description  : Given album name and corresponding directory, this scripts renames the jpg files with new name passed through command line
#Sample Input : ./rename_album.sh day_out ,
                \./rename_album.sh
#Sample Output:All .jpg files in current directory is renamed as
day_out001.jpg day_out002.jpg day_out003.jpg day_out005.jpg day_out004.jpg
DOC


if [ $# -eq 1 ]                                                         #Check for command line argument
then
    array=(`ls *.jpg`)                                                  #Get only .jpg file and store it in array
    for i in ${array[@]}
    do
        num=`echo $i | tr -cd [:digit:]`                                #Get if any digit in filename
        mv $i $1$num.jpg                                                #Change file name to new name
    done
    echo All .jpg files in current directory is renamed as `ls *.jpg`   #All .jpg file renamed as name passed through command line
else
echo "Error : Please pass the prefix name through command line."
fi
