#!/bin/bash
<<DOC
#Name         : Akshitha S
#Date         : 31/10/2023
#Description  : Shell script to convert string lower to upper and upper to lower
#Sample Input : 1. ./upper_lower.sh file.txt
                        1 – Lower to upper
                        2 – Upper to lower
                Please select option : 1
                Please select option : 2
                ./upper_lower.sh file1.txt
                ./upper_lower.sh
#Sample Output: WHAT IS OS?
                WHAT ARE THE DIFFERENT OS?
                WHEN IS OS USED?
                WHAT IS PARTITION AND ITS USE?
                HOW MANY PARTITIONS CAN BE DONE?,

                what is os?
                what are the different os?
                when is os used?
                what is partition and its use?
                how many partitions can be done?

                Error: No contents inside the file.

                Error : Please pass the file name through command line.
DOC


if [ $# -eq 1 ]                                             #To Check for command line argument
then
  if [ -f $1 ]                                              #To check wheather file given present or not
  then
     if [ -s $1 ]                                           #To check file contain some content or not
     then
         echo "1 – Lower to upper"
         echo "2 – Upper to lower"
          read -p "Please select option:" choice            #Enter choice to lower to upper and upper to lower
          case $choice in
             1)
            cat $1 | tr [:lower:] [:upper:]                 #Change string to upper case
              ;;
             2)
             cat $1 | tr [:upper:] [:lower:]                #change string to lower case
              ;;
             *)
              echo "Please enter valid choice."
                 ;;
           esac
         else
            echo "Error: No contents inside the file."      #provide message if file has no content
        fi
   else
          echo "Error: No such $1 file present."            #provide message if file not present

    fi
else                                                        #Error message if command line argument not passed
    echo "Error : Please pass the file name through command line."
fi
