#!/bin/bash
<<DOC
#Name         : Akshitha S
#Date         : 25/10/23
#Description  : Write a script for arithetic calculator using command line arguments
#Sample Input : ./arithmatic_calc.sh 25 + 41,
                ./arithmatic_calc.sh 10 x 5,
                ./arithmatic_calc.sh 25 / 5,
                ./arithmatic_calc.sh 10.2 – 5.6,
                ./arithmatic_calc.sh,
                ./arithmatic_calc.sh 3.4
#Sample Output: 25 + 41 = 66, 10 x 5 = 50,
                25 / 5 = 5.00,
                10.2 – 5.6 = 4.6,
                Error : Please pass the arguments through command line.
                Usage:./arithmatic_calc.sh 2.3 + 6.7,
                Error:Please pass 3 arguments.
                Usage:./arithmatic_calc.sh 2.3 + 6.7
DOC

if [ $# -eq 0 ]     #check for the command line arguments
then

    echo "Error : Please pass the arguments through command line."
    echo "Usage:./arithmatic_calc.sh 2.3 + 6.7"

elif [ $# -eq 3 ]   #check for command line argument whether 3 argument passed or not

then

case $2 in                      #case statement to get basic calculation

    +) sum=`echo "$1+$3" | bc ` #Addition of two number

        echo "$1 $2 $3 = $sum"

        ;;

    -) sub=`echo "$1-$3" | bc `  #substraction of two number

        echo "$1 $2 $3 = $sub"

        ;;

    x) mul=`echo "$1*$3" | bc `  #Multiplication of Two Number

        echo "$1 $2 $3 = $mul"

        ;;

    /) div=`echo "scale=2; $1/$3 " | bc ` #Division of Two Number

        echo "$1 $2 $3 = $div"

        ;;

    *)

       echo "Error : Please enter valid operator"
esac
else

    echo "Error:Please pass 3 arguments."

    echo "Usage:./arithmatic_calc.sh 2.3 + 6.7"
fi
