#!/bin/bash
<<DOC
#Name         : Akshitha S
#Date         : 27/10/2023
#Description  : Write a script to delete empty lines from a file
#Sample Input : Hello


                How


                are


                you?
#Sample Output: Empty lines are deleted
        Hello
        How
        are
        you?
DOC


if [ $# -eq  1 ]

then

    sed -i '/^[[:space:]]*$/d' $1           #Command to delete empty lines, blank lines from file
    echo "Empty lines are deleted"
    cat $1
else
    echo "Error: Please pass the file name through command line."  #if no file passed it will given an Error

fi
