#!/bin/bash
<<DOC
#Name         : Akshitha S
#Date         : 27/10/2023
#Description  : Write a script to print the length of each and every string using arrays
#Sample Input : Length of string (hello),
                Length of string (hai),
                Length of string (how),
                Length of string (are),
                Length of string (you?)
#Sample Output: 5,3,3,4

DOC

if [ $# -ne 0 ]                                                         #Check for command line arguments
then
    Array=( $@ )                                                        #Assigning Value to array
    for i in `seq 0 $((${#Array[*]}-1))`                                #Get number of elements
    do
        echo "Length of string (${Array[$i]}) - ${#Array[$i]}"          #Print the elements and length of element
    done
else
    echo "Error : Please pass the arguments through command-line."      #Print error message if command line arguments are not passed

fi
