#!/bin/bash
<<DOC
#Name         : Akshitha S
#Date         : 30/10/2023
#Description  : Write a script to sort a given number in ascending or descending order.
#Sample Input : ./sorting.sh -a 5 4 6 2 3 8 9 7 1,
                ./sorting.sh -d 5 4 6 2 3 8 9 7 1,
                ./sorting.sh 5 4 6 2 3 8 9 7 1,
                ./sorting.sh,
                ./sorting.sh -d 5 4 6 2 -3 8 -9 7 1
#Sample Output: Ascending order of array is 1 2 3 4 5 6 7 8 9,
                Descending order of array is 9 8 6 5 4 3 2 1,
                Error : Please pass the choice.
                Usage : ./sorting -a/-d 4 23 5 6 3,
                Error : Please pass the argument through command line.
                Usage : ./sorting -a/-d 4 23 5 6 3,
                Descending order of array is 8 7 6 5 4 2 1 -3 -9

DOC

if [ $# -ne 0 ]                                             #Check for command line argument is passed or not
then
array=($@)                                                  # To store the command line argument  in an array
len=$1                                                      #Get option for ascending and descending
case $len in                                                #case statement for Ascending and descending
   -a)
     for i in `seq $(($#-1))`                               #Ascending given Array
     do
        for j in `seq 1 $(($#-$i-1))`
        do
           if [ ${array[$j]} -gt ${array[$(($j+1))]} ]       #If array number grater than next number swap number
           then                                              #store in array
           large=${array[$j]}
           array[$j]=${array[$(($j+1))]}
           array[$(($j+1))]=$large
           fi
         done
      done
      echo "Ascending order of array is ${array[@]:1}"        #Display the given array in Ascending order
       ;;
   -d)
       for i in `seq $(($#-1))`                               #Case statement for descending order
       do
           for j in `seq 1 $(($#-$i-1))`
           do
               if [ ${array[$j]} -lt ${array[$(($j+1))]} ]    #Condition for the value less than next value
               then
               small=${array[$j]}                             #If less than swap the values and store it in array
               array[$j]=${array[$(($j+1))]}
               array[$(($j+1))]=$small
               fi
           done
       done
       echo "Descending order of array is ${array[@]:1}"      #Display ths descending order of array
       ;;
   *)
      echo "Error : Please pass the choice."
      echo "Usage : ./sorting -a/-d 4 23 5 6 3"
      ;;
  esac
  else
      echo "Error : Please pass the argument through command line."
      echo "Usage : ./sorting -a/-d 4 23 5 6 3"
  fi
